### PR TITLE
simplify function to get menu icons

### PR DESCRIPTION
**Pull request by pablo-jurado**
Create one function that handles all the menu icons.

### CODE REVIEW

**Comment by jennypenfield** [comment]
Hey, Pablo. Thanks! Won't this produce a maximum of one icon per menu item? Can we check if statements, add to the string, and return the string at the end?

**Comment by pablo-jurado** [comment]
You are totally right, I didn't think about that. Let me see if I can fix it

**Comment by pablo-jurado** [comment]
ok, it is fixed. Now is adding each icon to a variable and at the end is returning that variable

**Comment by jennypenfield** [comment]
Thanks, that is much improved!

**Pull request merged**
